name: D

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@v1

    - name: Install GDC
      run: sudo apt install gdc

    - name: Build and TAR
      run: |
        make strip
        tar -czf "trash-$(gcc -dumpmachine).tar.gz" trash
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        path: "trash-*.tar.gz"
