name: D

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-pandoc@v1
    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: ldc-latest

    - name: Test
      run: dub test --coverage --compiler=$DC

    - name: Build
      run: |
        dub build --build=release --compiler=$DC
        strip trash

    - name: Man Page with Pandoc
      run: "pandoc -s -t man -o trash.man MANUAL.md"

    - name: Distro Packages
      run: |
        sudo gem install fpm
        ruby package.rb

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: "trash-d"
        path: |
              trash
              trash.man
  
    - name: Upload Coverage Logs
      uses: actions/upload-artifact@v2
      with:
        name: "coverage-logs"
        path: "*.lst"

    - name: Upload Packages
      uses: actions/upload-artifact@v2
      with:
        name: "built-packages"
        path: "pkg/*"
