name: D

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: ldc-latest

    - name: Build & Test
      run: |
        dub build --build=release --compiler=$DC
        dub test --compiler=$DC
        strip trash
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: "trash-d"
        path: "trash"
